### ISSUE TITLE
AppStore version

### ISSUE THREAD

**Issue by beerisgood** [PhorionTech/Kronos#2]
Can you build a AppStore version?

**Comment by rookuu** [comment]
Hey, thanks for the feature request. 

At the moment we have no plans to release an App Store version of Kronos. Unfortunately, this would be a significant uplift given Apple's more strict requirements for an App Store app that aren't currently a priority . This includes issues with sandboxing (I don't believe you can sandbox a ES ext, but would need to double check) and removing our use of private frameworks at a minimum. 

We will keep this in mind in case it becomes feasible later down the line.

**Comment by beerisgood** [comment]
Fair enough 🍻
