### ISSUE TITLE
High CPU and Memory usage

### ISSUE THREAD

**Issue by WardsParadox** [PhorionTech/Kronos#3]
I've been seeing Kronos take well over 150% CPU and flashes of 500+ MB while running https://github.com/redcanaryco/mac-monitor. Even when not running, the extension continues to take over 70% CPU consistently and with the spikes, continues to stutter my laptop (M1 Pro, 32GB ram). 

Is there a way to uninstall the system extension to test additional performance issues with this?

**Comment by rookuu** [comment]
When you're seeing Kronos hit high CPU, is this the system extension or the app itself?

**Comment by WardsParadox** [comment]
System Extension.

**Comment by rookuu** [comment]
Cool, okay. If you drag the app to trash, it should prompt you to uninstall the system extension with it for the time being if it's causing issues. The app wont work at all without the system extension and it just displays a frontend to the data. We'll add a button to manually uninstall this in next minor.

But before you do that, if you open up the sys ext process in activity monitor and click the sample button, that'll generate a file you can send to me and i'll try to further diagnose this.

I've got two test machines including a really old intel that both work at between 5-10% on a single core (activity monitor shows percentages in relation to a single core), so this surprises me slightly. My only guess could be if you've got something that's doing very heavy file writes then the ESF client could be getting hammered, in the next minor version I'll add a config switch to disable the ESF client and we can see if this brings it down.

That said, I tried using Mac Monitor along side and I don't see any meaningful performance spike 🙈 Let me start with the sample and I'll see how far we can get. 

Thanks for the report!

**Comment by WardsParadox** [comment]
Will do! I rebooted the machine fresh this morning and the extension started out at 70% CPU usage with nothing running 😬 

I'll get things reinstalled and start testing further.

**Comment by WardsParadox** [comment]
So after two days of running this and having various items running (Canary, builds of various tools, etc). I've seen the Kronos extension settle in to quite good memory usage, using on <100 MB and rarely going above that before dropping back down (such as in a TCC prompt period)

CPU usage however seems to still jump around pretty often resulting in >70% usage on idle, averaging 30% CPU through out the day. That may be related to amount of agents on device (enterprise environment) doing various scans through out the day.

Here's a sample in case you want it:
[Sample of io.phorion.tcc-kronos.TCCKronosExtension.txt](https://github.com/PhorionTech/Kronos/files/13056217/Sample.of.io.phorion.tcc-kronos.TCCKronosExtension.txt)

I leave it up to you if you want to keep this open or not. I was on a beta3 of 14.1 and that may have been a root cause as well, especially seeing as it tripped out all TCC items causing a reset of the TCC db.

**Comment by rookuu** [comment]
Ah the plot thickens 😁 That's super useful info thanks. The sample is useful too, I have some ideas. 

We're planning on shipping a minor version very soon with the following features/fixes to address this;

- Switch unified log read mechanism to the private APIs that allow stream behaviour.
- Toggle switch for file open ESF events (used to detect tampering) in case it's that causing a performance issue.
- Various sentry config changes that might also be causing issues 😅 

Lets leave this open for now so it remains top of mind. When the next minor version ships I'll ping you in here but it should also prompt you to update (hopefully!) and we'll see if we get any improvement, 30% is still too high imo.

**Comment by WardsParadox** [comment]
Sounds good, looking forward to it. Tool has already been a help to build TCC profiles for a deployment so huge thanks :D

**Comment by WardsParadox** [comment]
<img width="686" alt="image" src="https://github.com/PhorionTech/Kronos/assets/8117192/610e90aa-e43c-42fa-9f92-6913696bf3b9">
[Sample of io.phorion.tcc-kronos.TCCKronosExtension.txt](https://github.com/PhorionTech/Kronos/files/13342143/Sample.of.io.phorion.tcc-kronos.TCCKronosExtension.txt)


So just idle activity, 27% usage. Memory seems to be completely fine though, max 50 MB. 

Just wanted to provide a sample while I was in the situation.

**Comment by rookuu** [comment]
Okay, we just released a couple new versions, 1.3.1 should be latest. Give that a try, you can update from the menubar. If there's no improvement from the new release, try turning off this setting.

![Image](https://github.com/PhorionTech/Kronos/assets/15949637/63aa0e4d-56ee-43ea-83dc-33014e4cc270)

Let me know either way if it gets solved and we'll have a good idea of what it was! 🙂

**Comment by WardsParadox** [comment]
Wow, huge improvements after install. Down under 20 MB so far in memory, will monitor through out day :)

Average CPU over last bit is <10%. 

Huge win, thanks!

**Comment by WardsParadox** [comment]
So after a week, this new update is purring along perfectly. Works great, next to nothing in resource usage. Memory sitting at 20 MB, 1-2% on occasion. 

Nice work :) Feel free to close with that release 🎉

**Comment by rookuu** [comment]
Hoping that after a couple of weeks we're still nice and performant. If it ever creeps back up, please do reach back out!

Going to close this one for now 😀
