### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by fakepop** [PhorionTech/Kronos#6]
Could you please provide information on how to install? 

Thanks.

**Comment by rookuu** [comment]
Hey, I've updated the README with more instructions.

**https://github.com/PhorionTech/Kronos#install**

Essentially, follow the setup tab in the settings. If all the lights are 🟢 , then it's working.

**Comment by beerisgood** [comment]
@rookuu the images are not available. 404 error.

**Comment by rookuu** [comment]
Whoops. Try now!

**Comment by beerisgood** [comment]
Fixed! 👍

**Comment by fakepop** [comment]
I didn't even realize there was an app bundle 🤦.

Thank you.
